// This file is auto-generated by scripts/generate_api_reference.py
export const apiReferenceMarkdown = `
# SelfDB API Reference

Complete API reference generated by hitting live backend endpoints and capturing real request/response data. This script creates test data, exercises all endpoints, logs responses, and cleans up afterwards. Run: \`python scripts/generate_api_reference.py\`

## Configuration

\`\`\`yaml
selfdb_base_url: http://localhost:8000
selfdb_api_key: 'YOUR_API_KEY'
\`\`\`

### Authentication

**All requests** require the \`X-API-Key\` header:

\`\`\`bash
X-API-Key: YOUR_API_KEY
\`\`\`

### Protected Endpoints

Protected endpoints additionally require a Bearer token in the \`Authorization\` header:

\`\`\`bash
Authorization: Bearer YOUR_ACCESS_TOKEN
\`\`\`

**Token Flow:**

1. **Get Tokens:** Call \`/auth/login\` or \`/auth/register\` to receive both \`access_token\` and \`refresh_token\`
2. **Use Access Token:** Include the \`access_token\` in the \`Authorization: Bearer <token>\` header for protected endpoints
3. **Refresh Token:** When the \`access_token\` expires, call \`/auth/refresh\` with your \`refresh_token\` to obtain new tokens

## Health Endpoints

### Check if the backend API is healthy and reachable.

\`\`\`bash
curl -X GET "http://localhost:8000/health"
  -H "X-API-Key: YOUR_API_KEY"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "service": "backend",
  "status": "ready",
  "version": "v0.05 early beta",
  "environment": {
    "env": "dev",
    "debug": "true",
    "api_port": 8000,
    "api_key_configured": true,
    "admin_email": "admin@example.com"
  },
  "database": {
    "host": "postgres",
    "port": "6432",
    "database": "selfdb_dev",
    "user": "selfdb_dev_user"
  },
  "message": "Backend service is ready and configured"
}
\`\`\`

### Retrieve API version, service status, and configuration summary.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/status"
  -H "X-API-Key: YOUR_API_KEY"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "api_version": "v0.05 early beta",
  "services": {
    "backend": "ready",
    "storage_url": "http://storage:8001",
    "functions_url": "http://deno-runtime:8090"
  },
  "ports": {
    "api": 8000,
    "storage": 8001,
    "functions": 8090,
    "postgres": 6432,
    "frontend": 3000
  }
}
\`\`\`

## Authentication

### Create a new user account.

\`\`\`bash
curl -X POST "http://localhost:8000/auth/register"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Content-Type: application/json"
  -d '{
  "email": "newuser@example.com",
  "password": "Password123!",
  "first_name": "Jane",
  "last_name": "Doe"
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "access_token": "<access_token>",
  "refresh_token": "<refresh_token>",
  "token_type": "Bearer",
  "expires_in": 1800,
  "user": {
    "id": "796f2e84-66e7-4744-93d3-d4886dfb7b5f",
    "email": "docs_user_1762176745@example.com",
    "first_name": "Docs",
    "last_name": "User",
    "role": "USER",
    "is_active": true,
    "created_at": "2025-11-03T13:32:25.592487+00:00",
    "updated_at": "2025-11-03T13:32:25.592487+00:00",
    "last_login_at": null
  }
}
\`\`\`

### Authenticate a user and retrieve access and refresh tokens.

\`\`\`bash
curl -X POST "http://localhost:8000/auth/login"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Content-Type: application/json"
  -d '{
  "email": "newuser@example.com",
  "password": "Password123!"
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "access_token": "<access_token>",
  "refresh_token": "<refresh_token>",
  "token_type": "Bearer",
  "expires_in": 1800,
  "user": {
    "id": "796f2e84-66e7-4744-93d3-d4886dfb7b5f",
    "email": "docs_user_1762176745@example.com",
    "first_name": "Docs",
    "last_name": "User",
    "role": "USER",
    "is_active": true,
    "created_at": "2025-11-03T13:32:25.592487+00:00",
    "updated_at": "2025-11-03T13:32:25.592487+00:00",
    "last_login_at": "2025-11-03T13:32:25.840642+00:00"
  }
}
\`\`\`

### Exchange a refresh token for a new access token.

\`\`\`bash
curl -X POST "http://localhost:8000/auth/refresh"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Content-Type: application/json"
  -d '{
  "refresh_token": "YOUR_REFRESH_TOKEN"
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "access_token": "<access_token>",
  "refresh_token": "<refresh_token>",
  "token_type": "Bearer",
  "expires_in": 1800,
  "user": {
    "id": "796f2e84-66e7-4744-93d3-d4886dfb7b5f",
    "email": "docs_user_1762176745@example.com",
    "first_name": "Docs",
    "last_name": "User",
    "role": "USER",
    "is_active": true,
    "created_at": "2025-11-03T13:32:25.592487+00:00",
    "updated_at": "2025-11-03T13:32:25.592487+00:00",
    "last_login_at": "2025-11-03T13:32:25.840642+00:00"
  }
}
\`\`\`

### Retrieve the currently authenticated user's profile.

\`\`\`bash
curl -X GET "http://localhost:8000/auth/me"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "id": "796f2e84-66e7-4744-93d3-d4886dfb7b5f",
  "email": "docs_user_1762176745@example.com",
  "first_name": "Docs",
  "last_name": "User",
  "role": "USER",
  "is_active": true,
  "created_at": "2025-11-03T13:32:25.592487+00:00",
  "updated_at": "2025-11-03T13:32:25.592487+00:00",
  "last_login_at": "2025-11-03T13:32:25.840642+00:00"
}
\`\`\`

### Change the authenticated user's password.

\`\`\`bash
curl -X POST "http://localhost:8000/auth/change-password"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "current_password": "OldPassword123!",
  "new_password": "NewPassword123!"
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "message": "Password changed successfully"
}
\`\`\`

## User Management

### Create a new user (admin only).

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/users"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "email": "user@example.com",
  "password": "Password123!",
  "first_name": "Jane",
  "last_name": "Doe"
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "id": "15848f20-a4c7-45e6-8e4c-c7ed6f3e5d7f",
  "email": "docs_admin_user_1762176746@example.com",
  "first_name": "Docs",
  "last_name": "AdminUser",
  "role": "USER",
  "is_active": true,
  "created_at": "2025-11-03T13:32:26.746927+00:00",
  "updated_at": "2025-11-03T13:32:26.746927+00:00",
  "last_login_at": null
}
\`\`\`

### List users with pagination (admin only).

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/users"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "users": [
    {
      "id": "15848f20-a4c7-45e6-8e4c-c7ed6f3e5d7f",
      "email": "docs_admin_user_1762176746@example.com",
      "first_name": "Docs",
      "last_name": "AdminUser",
      "role": "USER",
      "is_active": true,
      "created_at": "2025-11-03T13:32:26.746927+00:00",
      "updated_at": "2025-11-03T13:32:26.746927+00:00",
      "last_login_at": null
    },
    {
      "id": "796f2e84-66e7-4744-93d3-d4886dfb7b5f",
      "email": "docs_user_1762176745@example.com",
      "first_name": "Docs",
      "last_name": "User",
      "role": "USER",
      "is_active": true,
      "created_at": "2025-11-03T13:32:25.592487+00:00",
      "updated_at": "2025-11-03T13:32:26.292174+00:00",
      "last_login_at": "2025-11-03T13:32:25.840642+00:00"
    },
    {
      "id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
      "email": "admin@example.com",
      "first_name": "Admin",
      "last_name": "User",
      "role": "ADMIN",
      "is_active": true,
      "created_at": "2025-11-03T12:49:12.407912+00:00",
      "updated_at": "2025-11-03T12:49:12.407912+00:00",
      "last_login_at": "2025-11-03T13:32:26.516100+00:00"
    }
  ],
  "pagination": {
    "total": 3,
    "limit": 50,
    "offset": 0,
    "has_more": false
  }
}
\`\`\`

### Get total user count (admin only).

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/users/count"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (404)**:

\`\`\`json
{
  "detail": "User not found"
}
\`\`\`

### Get user details by ID (admin only).

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/users/{user_id}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "id": "15848f20-a4c7-45e6-8e4c-c7ed6f3e5d7f",
  "email": "docs_admin_user_1762176746@example.com",
  "first_name": "Docs",
  "last_name": "AdminUser",
  "role": "USER",
  "is_active": true,
  "created_at": "2025-11-03T13:32:26.746927+00:00",
  "updated_at": "2025-11-03T13:32:26.746927+00:00",
  "last_login_at": null
}
\`\`\`

### Update user fields such as role (admin only).

\`\`\`bash
curl -X PUT "http://localhost:8000/api/v1/users/{user_id}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "role": "ADMIN"
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "id": "15848f20-a4c7-45e6-8e4c-c7ed6f3e5d7f",
  "email": "docs_admin_user_1762176746@example.com",
  "first_name": "Docs",
  "last_name": "AdminUser",
  "role": "ADMIN",
  "is_active": true,
  "created_at": "2025-11-03T13:32:26.746927+00:00",
  "updated_at": "2025-11-03T13:32:26.788084+00:00",
  "last_login_at": null
}
\`\`\`

### Set a user's password (admin only).

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/users/{user_id}/password"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "new_password": "NewSecurePassword123!"
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "message": "Password updated successfully"
}
\`\`\`

### Delete a user (admin only).

\`\`\`bash
curl -X DELETE "http://localhost:8000/api/v1/users/{user_id}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "message": "User deleted successfully",
  "user_id": "15848f20-a4c7-45e6-8e4c-c7ed6f3e5d7f",
  "soft_deleted": false
}
\`\`\`

### Retrieve the configured API key for the authenticated user.

\`\`\`bash
curl -X GET "http://localhost:8000/auth/me/api-key"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "api_key": "dev_api_key_not_for_production"
}
\`\`\`

## Bucket Management

### Create a new storage bucket.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/buckets"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Content-Type: application/json"
  -d '{
  "name": "integration-bucket-6d0d21c4",
  "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
  "public": false
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "success": true,
  "bucket": {
    "name": "integration-bucket-6d0d21c4",
    "internal_bucket_name": "integration-bucket-6d0d21c4",
    "public": false
  }
}
\`\`\`

### Get bucket metadata by name.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/buckets/{bucket_id}"
  -H "X-API-Key: YOUR_API_KEY"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "success": true,
  "bucket": {
    "id": "f1fdbccd-3eb2-47b5-b94d-98602185ca3b",
    "name": "integration-bucket-6d0d21c4",
    "internal_bucket_name": "integration-bucket-6d0d21c4",
    "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
    "public": false,
    "description": null,
    "file_count": 0,
    "total_size": 0,
    "created_at": "2025-11-03T13:32:27.077346+00:00",
    "updated_at": "2025-11-03T13:32:27.077346+00:00"
  }
}
\`\`\`

## File Management

### Upload a file to a bucket using multipart form-data.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/files/upload"
  -H "X-API-Key: YOUR_API_KEY"
  -F 'bucket=test-bucket-64cead84'
  -F 'path=integration/docs_8c459084b60a.txt'
  # Files: file=@/path/to/local/file.txt
\`\`\`

**Response (200)**:

\`\`\`json
{
  "success": true,
  "message": "File uploaded successfully",
  "bucket": "test-bucket-64cead84",
  "path": "integration/docs_8c459084b60a.txt",
  "size": 41,
  "file_id": "d702a2d1-50dc-4df1-ab35-63d5f452fd46",
  "upload_time": null
}
\`\`\`

### Download a file from storage.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/files/{bucket}/{path}"
  -H "X-API-Key: YOUR_API_KEY"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "note": "Binary content streamed with Content-Disposition header"
}
\`\`\`

### Delete a file from a bucket.

\`\`\`bash
curl -X DELETE "http://localhost:8000/api/v1/files/{bucket}/{path}"
  -H "X-API-Key: YOUR_API_KEY"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "success": true,
  "message": "File deleted successfully",
  "bucket": "test-bucket-64cead84",
  "path": "integration/docs_8c459084b60a.txt"
}
\`\`\`

### List all files in a bucket.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/buckets/{bucket_id}/files"
  -H "X-API-Key: YOUR_API_KEY"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "success": true,
  "files": []
}
\`\`\`

## Table Management

### List all tables in the database.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/tables"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
[]
\`\`\`

### Create a new table with specified schema.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/tables"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "name": "products",
  "description": "Product catalog",
  "public": false,
  "schema": {
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "primary_key": true
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false
      },
      {
        "name": "price",
        "type": "numeric",
        "nullable": false
      }
    ]
  }
}'
\`\`\`

**Response (201)**:

\`\`\`json
{
  "name": "docs_table_b5c3e18cf711",
  "schema": {
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "primary_key": true
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false
      },
      {
        "name": "price",
        "type": "numeric",
        "nullable": false
      },
      {
        "name": "stock",
        "type": "integer",
        "nullable": true
      }
    ],
    "indexes": null
  },
  "public": false,
  "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
  "description": "Documentation example table",
  "metadata": {
    "creation_sql": "CREATE TABLE \"docs_table_b5c3e18cf711\" (\"id\" uuid DEFAULT uuid_generate_v4(), \"name\" text NOT NULL, \"price\" numeric NOT NULL, \"stock\" integer, PRIMARY KEY (\"id\"))"
  },
  "row_count": 0,
  "created_at": "2025-11-03T13:32:27.145598+00:00",
  "updated_at": "2025-11-03T13:32:27.145598+00:00"
}
\`\`\`

### Get table schema and metadata.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/tables/{table_name}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "name": "docs_table_b5c3e18cf711",
  "schema": {
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "primary_key": true
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false
      },
      {
        "name": "price",
        "type": "numeric",
        "nullable": false
      },
      {
        "name": "stock",
        "type": "integer",
        "nullable": true
      }
    ],
    "indexes": null
  },
  "public": false,
  "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
  "description": "Documentation example table",
  "metadata": {
    "creation_sql": "CREATE TABLE \"docs_table_b5c3e18cf711\" (\"id\" uuid DEFAULT uuid_generate_v4(), \"name\" text NOT NULL, \"price\" numeric NOT NULL, \"stock\" integer, PRIMARY KEY (\"id\"))"
  },
  "row_count": 0,
  "created_at": "2025-11-03T13:32:27.145598+00:00",
  "updated_at": "2025-11-03T13:32:27.145598+00:00"
}
\`\`\`

### Get SQL CREATE statement for the table.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/tables/{table_name}/sql"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "sql": "CREATE TABLE \"docs_table_b5c3e18cf711\" (\n  \"id\" UUID DEFAULT uuid_generate_v4() NOT NULL PRIMARY KEY,\n  \"name\" TEXT NOT NULL,\n  \"price\" NUMERIC NOT NULL,\n  \"stock\" INTEGER\n);"
}
\`\`\`

### Insert a new row into the table.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/tables/{table_name}/data"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "id": "ca8f84ac-3db9-4f47-919f-4cc5d6144f27",
  "name": "Laptop",
  "price": 999.99,
  "stock": 50
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "id": "ca8f84ac-3db9-4f47-919f-4cc5d6144f27",
  "name": "Laptop",
  "price": 999.99,
  "stock": 50
}
\`\`\`

### Retrieve rows from the table with optional filters, pagination, and ordering.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/tables/{table_name}/data"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "data": [
    {
      "id": "1de47250-e640-40a7-ac8f-6e69d290c96a",
      "name": "Mouse",
      "price": "25.5",
      "stock": 200
    },
    {
      "id": "ca8f84ac-3db9-4f47-919f-4cc5d6144f27",
      "name": "Laptop",
      "price": "999.990000000000009094947017729282379150390625",
      "stock": 50
    }
  ],
  "metadata": {
    "total_count": 2,
    "page": 1,
    "page_size": 10,
    "total_pages": 1,
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "primary_key": true
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false
      },
      {
        "name": "price",
        "type": "numeric",
        "nullable": false
      },
      {
        "name": "stock",
        "type": "integer",
        "nullable": true
      }
    ]
  }
}
\`\`\`

### Filter rows by column value.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/tables/{table_name}/data?filter_column={column}&filter_value={value}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "data": [
    {
      "id": "ca8f84ac-3db9-4f47-919f-4cc5d6144f27",
      "name": "Laptop",
      "price": "999.990000000000009094947017729282379150390625",
      "stock": 50
    }
  ],
  "metadata": {
    "total_count": 1,
    "page": 1,
    "page_size": 100,
    "total_pages": 1,
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "primary_key": true
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false
      },
      {
        "name": "price",
        "type": "numeric",
        "nullable": false
      },
      {
        "name": "stock",
        "type": "integer",
        "nullable": true
      }
    ]
  }
}
\`\`\`

### Update an existing row by ID.

\`\`\`bash
curl -X PUT "http://localhost:8000/api/v1/tables/{table_name}/data/{row_id}?id_column=id"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "stock": 75,
  "price": 1099.99
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "id": "ca8f84ac-3db9-4f47-919f-4cc5d6144f27",
  "name": "Laptop",
  "price": 1099.99,
  "stock": 75
}
\`\`\`

### Add a new column to the table.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/tables/{table_name}/columns"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "name": "category",
  "type": "text",
  "nullable": true
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "status": "column_added"
}
\`\`\`

### Update a column definition.

\`\`\`bash
curl -X PUT "http://localhost:8000/api/v1/tables/{table_name}/columns/{column_name}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "type": "varchar(255)",
  "nullable": false
}'
\`\`\`

**Response (409)**:

\`\`\`json
{
  "detail": "Constraint violation: column \"category\" of relation \"docs_table_b5c3e18cf711\" contains null values"
}
\`\`\`

### Update table metadata (description, public flag).

\`\`\`bash
curl -X PUT "http://localhost:8000/api/v1/tables/{table_name}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "description": "Updated description",
  "public": true
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "name": "docs_table_b5c3e18cf711",
  "schema": {
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "primary_key": true
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false
      },
      {
        "name": "price",
        "type": "numeric",
        "nullable": false
      },
      {
        "name": "stock",
        "type": "integer",
        "nullable": true
      },
      {
        "name": "category",
        "type": "text",
        "unique": false,
        "default": null,
        "nullable": true,
        "primary_key": false
      }
    ],
    "indexes": null
  },
  "public": true,
  "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
  "description": "Updated product inventory",
  "metadata": {
    "creation_sql": "CREATE TABLE \"docs_table_b5c3e18cf711\" (\"id\" uuid DEFAULT uuid_generate_v4(), \"name\" text NOT NULL, \"price\" numeric NOT NULL, \"stock\" integer, PRIMARY KEY (\"id\"))"
  },
  "row_count": 1,
  "created_at": "2025-11-03T13:32:27.145598+00:00",
  "updated_at": "2025-11-03T13:32:27.224756+00:00"
}
\`\`\`

### Delete a row from the table by ID.

\`\`\`bash
curl -X DELETE "http://localhost:8000/api/v1/tables/{table_name}/data/{row_id}?id_column=id"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (204)**:

\`\`\`json
{
  "note": "204 No Content on success"
}
\`\`\`

## SQL Execution

### Execute a SQL query against the database.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/sql/query"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "query": "SELECT * FROM users LIMIT 10"
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "success": true,
  "is_read_only": true,
  "execution_time": 0.0012521743774414062,
  "row_count": 1,
  "columns": [
    "result",
    "message"
  ],
  "data": [
    {
      "result": 1,
      "message": "Hello"
    }
  ],
  "message": "Query executed successfully in 0.00s",
  "error": null,
  "operations_summary": null
}
\`\`\`

### Execute DDL queries (CREATE, ALTER, DROP).

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/sql/query"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "query": "CREATE TABLE temp (id INTEGER, name TEXT)"
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "success": true,
  "is_read_only": false,
  "execution_time": 0.013916730880737305,
  "row_count": 1,
  "columns": [
    "Operation",
    "Object Type",
    "Object Name",
    "Details",
    "Status"
  ],
  "data": [
    {
      "Operation": "CREATE",
      "Object Type": "TABLE",
      "Object Name": "docs_temp_1762176747",
      "Details": "2 columns",
      "Status": "✅ Registered in metadata"
    }
  ],
  "message": "✅ Created 1 table in 0.01s. 1 table registered in SelfDB.",
  "error": null,
  "operations_summary": {
    "tables_created": 1,
    "tables_registered": 1,
    "total_operations": 1
  }
}
\`\`\`

### Save a query and its result to history.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/sql/history"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "query": "SELECT * FROM users",
  "result": {
    "success": true,
    "data": []
  }
}'
\`\`\`

**Response (201)**:

\`\`\`json
{
  "message": "Query saved to history"
}
\`\`\`

### Retrieve query execution history for the authenticated user.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/sql/history"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "history": [
    {
      "id": "bc126429-1a24-4cf8-b709-6c77a5515cf5",
      "query": "SELECT 123 as value",
      "is_read_only": true,
      "execution_time": 0.0012521743774414062,
      "row_count": 1,
      "error": null,
      "executed_at": "2025-11-03T13:32:27.301022",
      "user_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74"
    }
  ]
}
\`\`\`

### Save a SQL query snippet for reuse.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/sql/snippets"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "name": "Get active users",
  "sql_code": "SELECT * FROM users WHERE is_active = true",
  "description": "Query to fetch all active users",
  "is_shared": false
}'
\`\`\`

**Response (201)**:

\`\`\`json
{
  "id": "121b271a-0c46-4dd6-9def-ac9b09f67d18",
  "name": "Get active users 1762176747",
  "sql_code": "SELECT * FROM users WHERE is_active = true",
  "description": "Query to fetch all active users",
  "is_shared": false,
  "created_at": "2025-11-03T13:32:27.307485",
  "created_by": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74"
}
\`\`\`

### List all saved SQL snippets for the authenticated user.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/sql/snippets"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
[
  {
    "id": "121b271a-0c46-4dd6-9def-ac9b09f67d18",
    "name": "Get active users 1762176747",
    "sql_code": "SELECT * FROM users WHERE is_active = true",
    "description": "Query to fetch all active users",
    "is_shared": false,
    "created_at": "2025-11-03T13:32:27.307485",
    "created_by": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74"
  }
]
\`\`\`

### Delete a SQL snippet.

\`\`\`bash
curl -X DELETE "http://localhost:8000/api/v1/sql/snippets/{snippet_id}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (204)**:

\`\`\`json
{
  "note": "204 No Content on success"
}
\`\`\`

## Functions

### List all functions owned by the authenticated user.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/functions"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "functions": [],
  "total": 0,
  "limit": 20,
  "offset": 0
}
\`\`\`

### Create a new serverless function bound to a webhook trigger.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/functions"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "name": "onboard-stripe-customer-a2f4c1f3",
  "code": "import nodemailer from \"npm:nodemailer@6.9.7\";\n\nexport default async function handler(request, context) {\n  const payload = await request.json();\n  const { email, first_name, last_name } = payload.data;\n  const { env } = context;\n\n  const registerResponse = await fetch(\"http://backend:8000/auth/register\", {\n    method: \"POST\",\n    headers: {\n      \"Content-Type\": \"application/json\",\n      \"X-API-Key\": env.API_KEY\n    },\n    body: JSON.stringify({\n      email,\n      password: \"ChangeMe123!\",\n      first_name,\n      last_name\n    })\n  });\n\n  if (!registerResponse.ok) {\n    console.error(\`Failed to create user: \${registerResponse.statusText}\`);\n  }\n\n  const transporter = nodemailer.createTransport({\n    host: env.SMTP_HOST,\n    port: parseInt(env.SMTP_PORT || \"587\"),\n    secure: env.SMTP_PORT === \"465\",\n    auth: {\n      user: env.SMTP_USER,\n      pass: env.SMTP_PASSWORD\n    }\n  });\n\n  await transporter.sendMail({\n    from: env.SMTP_FROM_EMAIL,\n    to: env.AUDIT_EMAIL_TO,\n    subject: \"Thank you for buying SelfDB\",\n    html: \`\n      <h2>New onboarding processed</h2>\n      <p>Customer: \${first_name} \${last_name} &lt;\${email}&gt;</p>\n      <p>This is an automated webhook notification.</p>\n    \`\n  });\n\n  return {\n    success: true,\n    user_created: registerResponse.ok,\n    email_sent: true,\n    message: \`User created and welcome email sent for \${email}\`\n  };\n}\n\nexport const triggers = [\n  {\n    type: \"webhook\",\n    webhook_id: \"stripe-checkout\"\n  }\n];\n",
  "description": "Stripe customer onboarding with email",
  "runtime": "deno",
  "env_vars": {
    "SMTP_HOST": "smtp.example.com",
    "SMTP_PORT": "587",
    "SMTP_USER": "user@example.com",
    "SMTP_PASSWORD": "smtp-password",
    "SMTP_FROM_EMAIL": "no-reply@example.com",
    "AUDIT_EMAIL_TO": "ops@example.com",
    "API_KEY": "YOUR_API_KEY"
  }
}'
\`\`\`

**Response (201)**:

\`\`\`json
{
  "id": "1f5c094a-e184-4852-9c98-7867582e10e4",
  "name": "onboard-stripe-customer-a2f4c1f3",
  "description": "Stripe customer onboarding with email",
  "code": "import nodemailer from \"npm:nodemailer@6.9.7\";\n\nexport default async function handler(request, context) {\n  const payload = await request.json();\n  const { email, first_name, last_name } = payload.data;\n  const { env } = context;\n\n  const registerResponse = await fetch(\"http://backend:8000/auth/register\", {\n    method: \"POST\",\n    headers: {\n      \"Content-Type\": \"application/json\",\n      \"X-API-Key\": env.API_KEY\n    },\n    body: JSON.stringify({\n      email,\n      password: \"ChangeMe123!\",\n      first_name,\n      last_name\n    })\n  });\n\n  if (!registerResponse.ok) {\n    console.error(\`Failed to create user: \${registerResponse.statusText}\`);\n  }\n\n  const transporter = nodemailer.createTransport({\n    host: env.SMTP_HOST,\n    port: parseInt(env.SMTP_PORT || \"587\"),\n    secure: env.SMTP_PORT === \"465\",\n    auth: {\n      user: env.SMTP_USER,\n      pass: env.SMTP_PASSWORD\n    }\n  });\n\n  await transporter.sendMail({\n    from: env.SMTP_FROM_EMAIL,\n    to: env.AUDIT_EMAIL_TO,\n    subject: \"Thank you for buying SelfDB\",\n    html: \`\n      <h2>New onboarding processed</h2>\n      <p>Customer: \${first_name} \${last_name} &lt;\${email}&gt;</p>\n      <p>This is an automated webhook notification.</p>\n    \`\n  });\n\n  return {\n    success: true,\n    user_created: registerResponse.ok,\n    email_sent: true,\n    message: \`User created and welcome email sent for \${email}\`\n  };\n}\n\nexport const triggers = [\n  {\n    type: \"webhook\",\n    webhook_id: \"stripe-checkout\"\n  }\n];\n",
  "runtime": "deno",
  "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
  "is_active": true,
  "deployment_status": "pending",
  "deployment_error": null,
  "version": 1,
  "timeout_seconds": 30,
  "memory_limit_mb": 512,
  "max_concurrent": 10,
  "env_vars": {
    "SMTP_HOST": "smtp.example.com",
    "SMTP_PORT": "587",
    "SMTP_USER": "user@example.com",
    "SMTP_PASSWORD": "smtp-password",
    "SMTP_FROM_EMAIL": "no-reply@example.com",
    "AUDIT_EMAIL_TO": "ops@example.com",
    "API_KEY": "dev_api_key_not_for_production"
  },
  "execution_count": 0,
  "execution_success_count": 0,
  "execution_error_count": 0,
  "last_executed_at": null,
  "avg_execution_time_ms": null,
  "last_deployed_at": null,
  "created_at": "2025-11-03T13:32:27.318130+00:00",
  "updated_at": "2025-11-03T13:32:27.318230+00:00"
}
\`\`\`

### Get function details by ID.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/functions/{function_id}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "id": "1f5c094a-e184-4852-9c98-7867582e10e4",
  "name": "onboard-stripe-customer-a2f4c1f3",
  "description": "Stripe customer onboarding with email",
  "code": "import nodemailer from \"npm:nodemailer@6.9.7\";\n\nexport default async function handler(request, context) {\n  const payload = await request.json();\n  const { email, first_name, last_name } = payload.data;\n  const { env } = context;\n\n  const registerResponse = await fetch(\"http://backend:8000/auth/register\", {\n    method: \"POST\",\n    headers: {\n      \"Content-Type\": \"application/json\",\n      \"X-API-Key\": env.API_KEY\n    },\n    body: JSON.stringify({\n      email,\n      password: \"ChangeMe123!\",\n      first_name,\n      last_name\n    })\n  });\n\n  if (!registerResponse.ok) {\n    console.error(\`Failed to create user: \${registerResponse.statusText}\`);\n  }\n\n  const transporter = nodemailer.createTransport({\n    host: env.SMTP_HOST,\n    port: parseInt(env.SMTP_PORT || \"587\"),\n    secure: env.SMTP_PORT === \"465\",\n    auth: {\n      user: env.SMTP_USER,\n      pass: env.SMTP_PASSWORD\n    }\n  });\n\n  await transporter.sendMail({\n    from: env.SMTP_FROM_EMAIL,\n    to: env.AUDIT_EMAIL_TO,\n    subject: \"Thank you for buying SelfDB\",\n    html: \`\n      <h2>New onboarding processed</h2>\n      <p>Customer: \${first_name} \${last_name} &lt;\${email}&gt;</p>\n      <p>This is an automated webhook notification.</p>\n    \`\n  });\n\n  return {\n    success: true,\n    user_created: registerResponse.ok,\n    email_sent: true,\n    message: \`User created and welcome email sent for \${email}\`\n  };\n}\n\nexport const triggers = [\n  {\n    type: \"webhook\",\n    webhook_id: \"stripe-checkout\"\n  }\n];\n",
  "runtime": "deno",
  "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
  "is_active": true,
  "deployment_status": "deployed",
  "deployment_error": null,
  "version": 1,
  "timeout_seconds": 30,
  "memory_limit_mb": 512,
  "max_concurrent": 10,
  "env_vars": {
    "API_KEY": "dev_api_key_not_for_production",
    "SMTP_HOST": "smtp.example.com",
    "SMTP_PORT": "587",
    "SMTP_USER": "user@example.com",
    "SMTP_PASSWORD": "smtp-password",
    "AUDIT_EMAIL_TO": "ops@example.com",
    "SMTP_FROM_EMAIL": "no-reply@example.com"
  },
  "execution_count": 0,
  "execution_success_count": 0,
  "execution_error_count": 0,
  "last_executed_at": null,
  "avg_execution_time_ms": null,
  "last_deployed_at": "2025-11-03T13:32:27.344881+00:00",
  "created_at": "2025-11-03T13:32:27.318130+00:00",
  "updated_at": "2025-11-03T13:32:27.344881+00:00"
}
\`\`\`

### Update an existing function.

\`\`\`bash
curl -X PUT "http://localhost:8000/api/v1/functions/{function_id}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "code": "import nodemailer from \"npm:nodemailer@6.9.7\";\n\nexport default async function handler(request, context) {\n  const payload = await request.json();\n  const { email, first_name, last_name } = payload.data;\n  const { env } = context;\n\n  const registerResponse = await fetch(\"http://backend:8000/auth/register\", {\n    method: \"POST\",\n    headers: {\n      \"Content-Type\": \"application/json\",\n      \"X-API-Key\": env.API_KEY\n    },\n    body: JSON.stringify({\n      email,\n      password: \"ChangeMe123!\",\n      first_name,\n      last_name\n    })\n  });\n\n  if (!registerResponse.ok) {\n    console.error(\`Failed to create user: \${registerResponse.statusText}\`);\n  }\n\n  const transporter = nodemailer.createTransport({\n    host: env.SMTP_HOST,\n    port: parseInt(env.SMTP_PORT || \"587\"),\n    secure: env.SMTP_PORT === \"465\",\n    auth: {\n      user: env.SMTP_USER,\n      pass: env.SMTP_PASSWORD\n    }\n  });\n\n  await transporter.sendMail({\n    from: env.SMTP_FROM_EMAIL,\n    to: env.AUDIT_EMAIL_TO,\n    subject: \"Thank you for buying SelfDB\",\n    html: \`\n      <h2>New onboarding processed</h2>\n      <p>Customer: \${first_name} \${last_name} &lt;\${email}&gt;</p>\n      <p>This is an automated webhook notification.</p>\n    \`\n  });\n\n  return {\n    success: true,\n    user_created: registerResponse.ok,\n    email_sent: true,\n    message: \`User created and welcome email sent for \${email}\`\n  };\n}\n\nexport const triggers = [\n  {\n    type: \"webhook\",\n    webhook_id: \"stripe-checkout\"\n  }\n];\n\n// Updated documentation example",
  "description": "Updated function description"
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "id": "1f5c094a-e184-4852-9c98-7867582e10e4",
  "name": "onboard-stripe-customer-a2f4c1f3",
  "description": "Updated function description",
  "code": "import nodemailer from \"npm:nodemailer@6.9.7\";\n\nexport default async function handler(request, context) {\n  const payload = await request.json();\n  const { email, first_name, last_name } = payload.data;\n  const { env } = context;\n\n  const registerResponse = await fetch(\"http://backend:8000/auth/register\", {\n    method: \"POST\",\n    headers: {\n      \"Content-Type\": \"application/json\",\n      \"X-API-Key\": env.API_KEY\n    },\n    body: JSON.stringify({\n      email,\n      password: \"ChangeMe123!\",\n      first_name,\n      last_name\n    })\n  });\n\n  if (!registerResponse.ok) {\n    console.error(\`Failed to create user: \${registerResponse.statusText}\`);\n  }\n\n  const transporter = nodemailer.createTransport({\n    host: env.SMTP_HOST,\n    port: parseInt(env.SMTP_PORT || \"587\"),\n    secure: env.SMTP_PORT === \"465\",\n    auth: {\n      user: env.SMTP_USER,\n      pass: env.SMTP_PASSWORD\n    }\n  });\n\n  await transporter.sendMail({\n    from: env.SMTP_FROM_EMAIL,\n    to: env.AUDIT_EMAIL_TO,\n    subject: \"Thank you for buying SelfDB\",\n    html: \`\n      <h2>New onboarding processed</h2>\n      <p>Customer: \${first_name} \${last_name} &lt;\${email}&gt;</p>\n      <p>This is an automated webhook notification.</p>\n    \`\n  });\n\n  return {\n    success: true,\n    user_created: registerResponse.ok,\n    email_sent: true,\n    message: \`User created and welcome email sent for \${email}\`\n  };\n}\n\nexport const triggers = [\n  {\n    type: \"webhook\",\n    webhook_id: \"stripe-checkout\"\n  }\n];\n\n// Updated documentation example",
  "runtime": "deno",
  "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
  "is_active": true,
  "deployment_status": "pending",
  "deployment_error": null,
  "version": 2,
  "timeout_seconds": 30,
  "memory_limit_mb": 512,
  "max_concurrent": 10,
  "env_vars": {
    "API_KEY": "dev_api_key_not_for_production",
    "SMTP_HOST": "smtp.example.com",
    "SMTP_PORT": "587",
    "SMTP_USER": "user@example.com",
    "SMTP_PASSWORD": "smtp-password",
    "AUDIT_EMAIL_TO": "ops@example.com",
    "SMTP_FROM_EMAIL": "no-reply@example.com"
  },
  "execution_count": 0,
  "execution_success_count": 0,
  "execution_error_count": 0,
  "last_executed_at": null,
  "avg_execution_time_ms": null,
  "last_deployed_at": "2025-11-03T13:32:27.344881+00:00",
  "created_at": "2025-11-03T13:32:27.318130+00:00",
  "updated_at": "2025-11-03T13:32:27.361666+00:00"
}
\`\`\`

## Webhooks

### List all webhooks for the authenticated user.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/webhooks"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "webhooks": [],
  "total": 0,
  "limit": 20,
  "offset": 0
}
\`\`\`

### Create a new webhook endpoint.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/webhooks"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
  -H "Content-Type: application/json"
  -d '{
  "name": "stripe-checkout-7810f712",
  "provider": "stripe",
  "provider_event_type": "checkout.session.completed",
  "secret_key": "whsec_your_secret_key",
  "function_id": "function-uuid"
}'
\`\`\`

**Response (201)**:

\`\`\`json
{
  "id": "a74265e1-b488-47de-98eb-2bf1efa5a285",
  "function_id": "1f5c094a-e184-4852-9c98-7867582e10e4",
  "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
  "name": "stripe-checkout-7810f712",
  "description": null,
  "provider": "stripe",
  "provider_event_type": "checkout.session.completed",
  "source_url": null,
  "webhook_token": "<webhook_token>",
  "path_segment": "stripe_xJVRuArcgVMTqsIZdC0tqBIltkO6PaAjAzu7XRBv_vI",
  "is_active": true,
  "rate_limit_per_minute": 100,
  "retry_attempts": 3,
  "retry_backoff_strategy": "exponential",
  "retry_delay_seconds": 60,
  "retry_max_delay_seconds": 3600,
  "last_received_at": null,
  "last_delivery_status": null,
  "successful_delivery_count": 0,
  "failed_delivery_count": 0,
  "total_delivery_count": 0,
  "created_at": "2025-11-03T13:32:27.375557+00:00",
  "updated_at": "2025-11-03T13:32:27.375557+00:00"
}
\`\`\`

### Get webhook details by ID.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/webhooks/{webhook_id}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "id": "a74265e1-b488-47de-98eb-2bf1efa5a285",
  "function_id": "1f5c094a-e184-4852-9c98-7867582e10e4",
  "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
  "name": "stripe-checkout-7810f712",
  "description": null,
  "provider": "stripe",
  "provider_event_type": "checkout.session.completed",
  "source_url": null,
  "webhook_token": "<webhook_token>",
  "path_segment": "stripe_xJVRuArcgVMTqsIZdC0tqBIltkO6PaAjAzu7XRBv_vI",
  "is_active": true,
  "rate_limit_per_minute": 100,
  "retry_attempts": 3,
  "retry_backoff_strategy": "exponential",
  "retry_delay_seconds": 60,
  "retry_max_delay_seconds": 3600,
  "last_received_at": null,
  "last_delivery_status": null,
  "successful_delivery_count": 0,
  "failed_delivery_count": 0,
  "total_delivery_count": 0,
  "created_at": "2025-11-03T13:32:27.375557+00:00",
  "updated_at": "2025-11-03T13:32:27.375557+00:00"
}
\`\`\`

### Ingest a webhook event payload.

\`\`\`bash
curl -X POST "http://localhost:8000/api/v1/webhooks/ingest/{function_id}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Content-Type: application/json"
  -H "X-Webhook-Signature: 7abfdd821fd0af9fa417642b1948987b1304a9a98c0d4e2d2c9e3ce18c442811"
  -d '{
  "id": "cs_test_d574bc754ee3",
  "object": "checkout.session",
  "amount_total": 2000,
  "currency": "usd",
  "customer_email": "aliceb81c3a3078ad@stripeonboarding-example.com",
  "customer_details": {
    "email": "aliceb81c3a3078ad@stripeonboarding-example.com",
    "name": "Alice Johnson"
  },
  "data": {
    "first_name": "Alice",
    "last_name": "Johnson",
    "email": "aliceb81c3a3078ad@stripeonboarding-example.com"
  }
}'
\`\`\`

**Response (200)**:

\`\`\`json
{
  "success": true,
  "message": "Webhook received and queued for execution",
  "execution_id": "3332ba17-aaf9-4ff7-9548-35fcaca6d052",
  "delivery_id": "f105ab89-df55-4a7f-a857-75f94836b02c",
  "function_id": "1f5c094a-e184-4852-9c98-7867582e10e4"
}
\`\`\`

### Get function details after webhook ingestion.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/functions/{function_id}"
  -H "X-API-Key: YOUR_API_KEY"
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "id": "1f5c094a-e184-4852-9c98-7867582e10e4",
  "name": "onboard-stripe-customer-a2f4c1f3",
  "description": "Updated function description",
  "code": "import nodemailer from \"npm:nodemailer@6.9.7\";\n\nexport default async function handler(request, context) {\n  const payload = await request.json();\n  const { email, first_name, last_name } = payload.data;\n  const { env } = context;\n\n  const registerResponse = await fetch(\"http://backend:8000/auth/register\", {\n    method: \"POST\",\n    headers: {\n      \"Content-Type\": \"application/json\",\n      \"X-API-Key\": env.API_KEY\n    },\n    body: JSON.stringify({\n      email,\n      password: \"ChangeMe123!\",\n      first_name,\n      last_name\n    })\n  });\n\n  if (!registerResponse.ok) {\n    console.error(\`Failed to create user: \${registerResponse.statusText}\`);\n  }\n\n  const transporter = nodemailer.createTransport({\n    host: env.SMTP_HOST,\n    port: parseInt(env.SMTP_PORT || \"587\"),\n    secure: env.SMTP_PORT === \"465\",\n    auth: {\n      user: env.SMTP_USER,\n      pass: env.SMTP_PASSWORD\n    }\n  });\n\n  await transporter.sendMail({\n    from: env.SMTP_FROM_EMAIL,\n    to: env.AUDIT_EMAIL_TO,\n    subject: \"Thank you for buying SelfDB\",\n    html: \`\n      <h2>New onboarding processed</h2>\n      <p>Customer: \${first_name} \${last_name} &lt;\${email}&gt;</p>\n      <p>This is an automated webhook notification.</p>\n    \`\n  });\n\n  return {\n    success: true,\n    user_created: registerResponse.ok,\n    email_sent: true,\n    message: \`User created and welcome email sent for \${email}\`\n  };\n}\n\nexport const triggers = [\n  {\n    type: \"webhook\",\n    webhook_id: \"stripe-checkout\"\n  }\n];\n\n// Updated documentation example",
  "runtime": "deno",
  "owner_id": "b6083c9a-ea6a-485f-8fd6-4a37445e6b74",
  "is_active": true,
  "deployment_status": "pending",
  "deployment_error": null,
  "version": 2,
  "timeout_seconds": 30,
  "memory_limit_mb": 512,
  "max_concurrent": 10,
  "env_vars": {
    "API_KEY": "dev_api_key_not_for_production",
    "SMTP_HOST": "smtp.example.com",
    "SMTP_PORT": "587",
    "SMTP_USER": "user@example.com",
    "SMTP_PASSWORD": "smtp-password",
    "AUDIT_EMAIL_TO": "ops@example.com",
    "SMTP_FROM_EMAIL": "no-reply@example.com"
  },
  "execution_count": 0,
  "execution_success_count": 0,
  "execution_error_count": 0,
  "last_executed_at": null,
  "avg_execution_time_ms": null,
  "last_deployed_at": "2025-11-03T13:32:27.344881+00:00",
  "created_at": "2025-11-03T13:32:27.318130+00:00",
  "updated_at": "2025-11-03T13:32:27.361666+00:00"
}
\`\`\`

## Realtime

### Realtime status and configuration.

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/realtime/status"
  -H "X-API-Key: YOUR_API_KEY"
\`\`\`

**Response (200)**:

\`\`\`json
{
  "service": "realtime",
  "status": "ready",
  "phoenix_enabled": "true",
  "phoenix_url": "http://realtime:4000"
}
\`\`\`

### Establish a WebSocket connection proxied to the Phoenix Realtime service (Phoenix Channels compatible).

\`\`\`bash
curl -X GET "http://localhost:8000/api/v1/realtime/ws?token=YOUR_JWT_TOKEN"
  -H "X-API-Key: YOUR_API_KEY"
\`\`\`

**Response (101)**:

\`\`\`json
{
  "note": "WebSocket upgrade. Use a WebSocket client such as the browser WebSocket API.",
  "client_usage": {
    "connect": "realtimeService.connect(token)",
    "subscribe": "realtimeService.subscribe('tables_events')",
    "unsubscribe": "realtimeService.unsubscribe('tables_events')"
  },
  "message_protocol": {
    "format": "[join_ref, ref, topic, event, payload]",
    "example_subscribe_payload": {
      "type": "subscribe",
      "resource_type": "tables",
      "resource_id": null
    },
    "example_broadcast": {
      "type": "broadcast",
      "channel": "tables_events",
      "payload": {
        "table": "orders",
        "operation": "INSERT"
      }
    }
  },
  "frontend_reference": "See frontend/src/services/realtimeService.ts for the client implementation used by Dashboard widgets."
}
\`\`\`

`;
