name: Copy to Hetzner Cloud Try 2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare target directory on Hetzner server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATEKEY }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Create selfdb directory if it doesn't exist
            echo "${{ secrets.PASSWORD }}" | sudo -S mkdir -p /home/selfdb
            
            # Set proper ownership and permissions
            echo "${{ secrets.PASSWORD }}" | sudo -S chown -R $USER:$USER /home/selfdb
            echo "${{ secrets.PASSWORD }}" | sudo -S chmod -R 755 /home/selfdb

      - name: Copy source code to Hetzner server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATEKEY }}
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: "/home/selfdb/"
          overwrite: true

      - name: Build and deploy on Hetzner server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATEKEY }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Navigate to project directory
            cd /home/selfdb/
            
            # Run startup script

            ./start.sh
